// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package clipboard

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockCopier creates a new instance of MockCopier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCopier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCopier {
	mock := &MockCopier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCopier is an autogenerated mock type for the Copier type
type MockCopier struct {
	mock.Mock
}

type MockCopier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCopier) EXPECT() *MockCopier_Expecter {
	return &MockCopier_Expecter{mock: &_m.Mock}
}

// Available provides a mock function for the type MockCopier
func (_mock *MockCopier) Available() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Available")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockCopier_Available_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Available'
type MockCopier_Available_Call struct {
	*mock.Call
}

// Available is a helper method to define mock.On call
func (_e *MockCopier_Expecter) Available() *MockCopier_Available_Call {
	return &MockCopier_Available_Call{Call: _e.mock.On("Available")}
}

func (_c *MockCopier_Available_Call) Run(run func()) *MockCopier_Available_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCopier_Available_Call) Return(b bool) *MockCopier_Available_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockCopier_Available_Call) RunAndReturn(run func() bool) *MockCopier_Available_Call {
	_c.Call.Return(run)
	return _c
}

// Copy provides a mock function for the type MockCopier
func (_mock *MockCopier) Copy(text string) error {
	ret := _mock.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for Copy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(text)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCopier_Copy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Copy'
type MockCopier_Copy_Call struct {
	*mock.Call
}

// Copy is a helper method to define mock.On call
//   - text string
func (_e *MockCopier_Expecter) Copy(text interface{}) *MockCopier_Copy_Call {
	return &MockCopier_Copy_Call{Call: _e.mock.On("Copy", text)}
}

func (_c *MockCopier_Copy_Call) Run(run func(text string)) *MockCopier_Copy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCopier_Copy_Call) Return(err error) *MockCopier_Copy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCopier_Copy_Call) RunAndReturn(run func(text string) error) *MockCopier_Copy_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockCopier
func (_mock *MockCopier) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCopier_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockCopier_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockCopier_Expecter) Name() *MockCopier_Name_Call {
	return &MockCopier_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockCopier_Name_Call) Run(run func()) *MockCopier_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCopier_Name_Call) Return(s string) *MockCopier_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCopier_Name_Call) RunAndReturn(run func() string) *MockCopier_Name_Call {
	_c.Call.Return(run)
	return _c
}
